language: node_js
node_js:
  - 8
  - 6
  - 4
cache:
  directories:
    - $HOME/.npm
    - node_modules
before_install:
  - npm install --global npm@5.4.2
  - npm --version
after_success: ./node_modules/.bin/codecov --file=./coverage/lcov.info
