build: off
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
clone_depth: 1
skip_branch_with_pr: true
skip_commits:
  files:
    - '**/*.md'
environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 6
    - nodejs_version: 4
matrix:
  fast_finish: true
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@5.4.2
  - npm --version
  - npm install
test_script:
  - npm run test
